services:
  - type: web
    name: game-theory-api
    runtime: docker
    plan: starter
    dockerfilePath: ./backend/Dockerfile
    dockerContext: .
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_NAME
        value: game-theory-api
      - key: APP_PORT
        value: "8000"
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        sync: false
